language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple_node_travis_ci .
  - docker tag simple_node_travis_ci hungdoan2023/simple_node_travis_ci:latest

after_success:
  - docker "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hungdoan2023/simple_node_travis_ci